---
name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - "*.*.*"

jobs:
  Deploy-to-docker:
    runs-on: self-hosted
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_WALLET_ID: ${{ secrets.NOTION_WALLET_ID }}
      SECRET_COOKIE_EXPIRES_DAYS: ${{ secrets.SECRET_COOKIE_EXPIRES_DAYS }}
      SECRET_COOKIE_NAME: ${{ secrets.SECRET_COOKIE_NAME }}
      SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD }}
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Deploy
        run: docker compose up --build --force-recreate -d
      - name: Clean up
        run: docker rmi $(docker images -f "dangling=true" -q)
